import { sidebar } from "vuepress-theme-hope";

export const sidebarZh = sidebar({
  "/": [
    "",
    {
      text: "大前端",
      icon: "laptop-code",
      prefix: "largeFront/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "后端",
      icon: "server",
      prefix: "backend/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "算法",
      icon: "calculator",
      prefix: "algorithm/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "浏览器",
      icon: "chrome",
      prefix: "browser/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "HTTP",
      icon: "globe",
      prefix: "http/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JavaScript",
      icon: "js",
      prefix: "javascript/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "ES6",
      icon: "code",
      prefix: "ES6/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "TypeScript",
      icon: "code",
      prefix: "typescript/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "CSS",
      icon: "css3-alt",
      prefix: "css/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "H5APP",
      icon: "mobile-screen",
      prefix: "h5app/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "移动端",
      icon: "mobile",
      prefix: "mobile_applet/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "插件",
      icon: "puzzle-piece",
      prefix: "plugins/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Vite",
      icon: "bolt",
      prefix: "vite/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "WebPack",
      icon: "boxes-stacked",
      prefix: "webpack/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "AI",
      icon: "robot",
      prefix: "AI/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "项目管理",
      icon: "tasks",
      prefix: "projectManagement/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Szkingdom",
      icon: "building",
      prefix: "szkingdom/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "金融",
      icon: "chart-line",
      prefix: "financial/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "随笔",
      icon: "pen-fancy",
      prefix: "writings/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "生活",
      icon: "heart",
      prefix: "life/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "旅游",
      icon: "plane",
      prefix: "travel/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "其他",
      icon: "folder",
      prefix: "other/",
      collapsible: true,
      children: "structure",
    },
  ],
});
