import { sidebar } from "vuepress-theme-hope"

export const sidebarZh = sidebar({
  "/": [
    "",
    {
      text: "大前端",
      icon: "laptop-code",
      prefix: "largeFront/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "后端",
      icon: "circle-info",
      prefix: "backend/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "算法",
      icon: "book",
      prefix: "algorithm/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "浏览器",
      icon: "book",
      prefix: "browser/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "HTTP",
      icon: "book",
      prefix: "http/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JAVASCRIPT",
      icon: "book",
      prefix: "javascript/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "ES6",
      icon: "book",
      prefix: "ES6/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "TypeScript",
      icon: "book",
      prefix: "typescript/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "CSS",
      icon: "book",
      prefix: "css/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "H5APP",
      icon: "book",
      prefix: "h5app/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "移动端",
      icon: "book",
      prefix: "mobile_applet/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "插件",
      icon: "book",
      prefix: "plugins/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Vite",
      icon: "book",
      prefix: "vite/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "WEBPACK",
      icon: "book",
      prefix: "webpack/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "AI",
      icon: "book",
      prefix: "AI/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "项目管理",
      icon: "book",
      prefix: "projectManagement/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Szkingdom",
      icon: "book",
      prefix: "szkingdom/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "金融",
      icon: "book",
      prefix: "financial/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "随笔",
      icon: "book",
      prefix: "writings/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "生活",
      icon: "book",
      prefix: "life/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "旅游",
      icon: "book",
      prefix: "travel/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "其他",
      icon: "book",
      prefix: "other/",
      collapsible: true,
      children: "structure",
    },
  ],
})
